### PR TITLE
binary search program in python added

### PR DESCRIPTION
**Pull request by Somsubhra1**
Binary search program

### CODE REVIEW

**Review by harikanani — CHANGES_REQUESTED** [review]
Can you please add more medium and difficult level programs

**Comment by adityamangal1** [comment]
Also, @Somsubhra1 change your description to add "program name" instead of fixes issues. Since it's not a fix

**Comment by adityamangal1** [comment]
@Somsubhra1 make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by Somsubhra1** [comment]
Added Kosaraju's algorithm to find strongly connected components in a directed graph

**Review by adityamangal1 — APPROVED** [review]

**Review by Nitesh-thapliyal — APPROVED** [review]

**Review by harikanani — APPROVED** [review]

**Review by abhigoyani — APPROVED** [review]

**Pull request merged**
