### PR TITLE
Created StackAsList.py

### PR DESCRIPTION
**Pull request by EFFLUX110**
python program in which most of the basic concepts of linear data structures will be cleared like :
# For stacks:
* #Insertion of Element  (Push)
* #Deletion of Element  (Pop)
* #Inpection of top element  (Peek)
* #Display of Stack Elements  (Display)

### CODE REVIEW

**Review by harikanani — COMMENTED** [review]
LGTM ✔

**Review by aayush89890 — COMMENTED** [review]
Looks Good...Thanks for your contribution @EFFLUX110

**Comment by EFFLUX110** [comment]
> Looks Good...Thanks for your contribution @EFFLUX110

_thank you very much_

**Comment by kevalvavaliya** [comment]
Good job @EFFLUX110

**Comment by EFFLUX110** [comment]
> Good job @EFFLUX110

thanks, but when it will be merged? 🔢

**Pull request merged**
