### PR TITLE
Added 4 medium and hard level codeforces solutions

### PR DESCRIPTION
**Pull request by theEllusionist**

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @theEllusionist, Have you forked the repo or editing directly? Bcoz there is no need to open a new PR if you have done changes by forking and cloning the repo

**Comment by theEllusionist** [comment]
I have forked the repo.

**Review by adityamangal1 — APPROVED** [review]

**Review by kevalvavaliya — APPROVED** [review]
Looks Good to me ✅

Thanks for your valuable contribution 😎.

**Review by harikanani — APPROVED** [review]
Looks Good to me ✅

**Review by abhigoyani — APPROVED** [review]

**Pull request merged**
