### PR TITLE
Added Sorting Folder

### PR DESCRIPTION
**Pull request by Geek-Tekina**
Want to contribute as Contributor in Hactoberfest 2021

### CODE REVIEW

**Comment by princesrivastava786** [comment]
@Geek-Tekina Can you please add more 3-4 medium and difficult level programs

**Review by harikanani — CHANGES_REQUESTED** [review]
Add `Sorting` folder in `Data_Structure_And_Algorithms`

**Comment by Geek-Tekina** [comment]
Ok sir ..on it.

**Comment by harikanani** [comment]
> Ok sir ..on it.

Mean While Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted😊.

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Comment by Geek-Tekina** [comment]
Changes Done sir.

**Comment by Geek-Tekina** [comment]
Sir Why this pr is not showing in pull request?

**Comment by Geek-Tekina** [comment]
Sir in Labels Hactoberfest is not mentioned !!!! @harikanani

**Review by kevalvavaliya — APPROVED** [review]
Thanks For Your valuable contibution

**Comment by Geek-Tekina** [comment]
Happy Contributing With You .

**Pull request merged**
