### PR TITLE
Adding 4 Java Leetcode solutions

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
#34

### CODE REVIEW

**Review by adityamangal1 — APPROVED** [review]
LGTM

**Review by harikanani — APPROVED** [review]
Looks Good to me ✅

Thanks for your valuable contribution 😎.

**Review by abhigoyani — APPROVED** [review]
LGTM

**Review by kevalvavaliya — APPROVED** [review]

**Review by Piyush-Codes7 — APPROVED** [review]

**Comment by mohitsaxenaknoldus** [comment]
Why is this marked as `Do-Not-Merge`? Is there something wrong that needs change?

**Comment by adityamangal1** [comment]
> Why is this marked as `Do-Not-Merge`? Is there something wrong that needs change?

Hey @mohitsaxenaknoldus Not to worry this label is just for some time while all reviewers are reviewing

**Pull request merged**
