### PR TITLE
feat : Added Js folder

### PR DESCRIPTION
**Pull request by Rajkumar-justcoder**
### Added js folder

adding Js folder in coding
added Js files from freecodecamp

### CODE REVIEW

**Review by Nitesh-thapliyal — CHANGES_REQUESTED** [review]
Hey, great work!!🎉 but can you remove the basics file and add the topic related code.

**Comment by Rajkumar-stackcoder** [comment]
Changes Done

**Comment by Rajkumar-stackcoder** [comment]
@Nitesh-thapliyal

**Comment by adityamangal1** [comment]
Replace java by javascript here also there is a typo in 9 line @Rajkumar-stackcoder

**Comment by Rajkumar-stackcoder** [comment]
Okay changing in some time @adityamangal1 
Thanks for the telling typo mistake

**Comment by Rajkumar-stackcoder** [comment]
### Changes done


> 
> 
> Okay changing in some time @adityamangal1 Thanks for the telling typo mistake

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
