### PR TITLE
Create (Easy) 860. Lemonade Change

### PR DESCRIPTION
**Pull request by stutimongia2024**

### CODE REVIEW

**Review by harikanani — COMMENTED** [review]
It would be great if you add more medium and difficult-level problem solutions.

you have already contributed to this repository for hacktoberfest once so try to explore more repositories on our organization.

Thanks for your contributions 😎

**Comment by stutimongia2024** [comment]
sure thankyou. @harikanani 
I wasn't assigned the issue for the contribution I have made in this repo earlier. So it would be helpful if you check that once.

**Comment by harikanani** [comment]
> sure thankyou. @harikanani I wasn't assigned the issue for the contribution I have made in this repo earlier. So it would be helpful if you check that once.

Yes, I have reviewed it as I can see you've already contributed to this repository once and your PR got merged so kindly check the other repo as well.
you can still add more problem solutions to this repo but we're counting one PR per repository for hacktoberfest

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
Thanks for your Valuable Contribution : )

**Pull request merged**
