### PR TITLE
Added 5 codeforces questions.

### PR DESCRIPTION
**Pull request by Yakshit310**

### CODE REVIEW

**Review by adityamangal1 — APPROVED** [review]
LGTM

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 

Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Review by harikanani — APPROVED** [review]
Looks Good to me ✅.
Thank you for your valuable contribution 😊.

**Review by kevalvavaliya — APPROVED** [review]
✅Looks Great

**Review by abhigoyani — APPROVED** [review]

**Pull request merged**
