### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yashsanghvi001**
added sorting folder and sorting algo in DSA

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @yashsanghvi001, Can you add 2-3 more medium level or hard questions more?

**Review by kevalvavaliya — APPROVED** [review]

**Review by harikanani — CHANGES_REQUESTED** [review]
Can you please add 3-4 more medium or difficult-level problem solutions?

**Comment by yashsanghvi001** [comment]
I have added more solutions of the CodeChef problem which is previously solved by me.

**Review by kevalvavaliya — APPROVED** [review]
Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Pull request merged**
