### PR TITLE
Bubble sort added

### PR DESCRIPTION
**Pull request by rishigupta1109**
added bubble sort and its questions
 issue #45

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @rishigupta1109 Can you add 3-4 more medium or hard level question also change the description to add questions instead fixes issue

**Comment by rishigupta1109** [comment]
okay

**Comment by adityamangal1** [comment]
Also @rishigupta1109  make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Comment by rishigupta1109** [comment]
sure. Thanks😊

**Comment by rishigupta1109** [comment]
@adityamangal1 Added the questions as you said.😊

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
