### PR TITLE
Added 4 problems from Codechef starters 9

### PR DESCRIPTION
**Pull request by div-sahu55**
Added more codechef questions. Thanks!

### CODE REVIEW

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
Thanks for your valuable contribution : )

**Review by abhigoyani — APPROVED** [review]
👍

**Comment by div-sahu55** [comment]
Contest Name - Codechef Starters 9
Contest Link - https://www.codechef.com/START9C

**Review by adityamangal1 — APPROVED** [review]

**Review by kevalvavaliya — COMMENTED** [review]
LGTM 
Go Ahead
 Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech/

**Pull request merged**
