### PR TITLE
largest integer element in array

### PR DESCRIPTION
**Pull request by shruti73**
I have created an c++ program in which we can find largest integer number in an array.

### CODE REVIEW

**Comment by kamleshjoshi8102** [comment]
@shruti73 Have you changed Bubble sort too?

**Comment by shruti73** [comment]
yes

**Comment by harikanani** [comment]
@shruti73 can you please add more 2-3 problem solution?

**Review by adityamangal1 — CHANGES_REQUESTED** [review]
Please make changes as @harikanani requested

**Pull request merged**
