### PR TITLE
added leetcode(96) Unique Binary Search Trees

### PR DESCRIPTION
**Pull request by kajalp23**
Leetcode medium level problem 96)Unique Binary Search Trees added

### CODE REVIEW

**Comment by adityamangal1** [comment]
Hey @kajalp23, Make sure to join the organization and discord server first so that your contribution is counted as hacktoberfest accepted.😊

Organization link👉 https://github.com/Bauddhik-Geeks/Welcome-to-Bauddhik-Geeks
Discord server link 👉 https://join.bauddhikgeeks.tech

**Review by abhigoyani — CHANGES_REQUESTED** [review]
Can you please add 2-3 more  hard or medium-level problem solutions ?

**Comment by kajalp23** [comment]
changes done

**Review by harikanani — APPROVED** [review]
Looks Good to me now ✅

Thanks for your contribution 🙌

**Review by kamleshjoshi8102 — APPROVED** [review]
LGTM 
Thanks for your valuable contribution : )

**Review by adityamangal1 — APPROVED** [review]

**Pull request merged**
